---
title: "888_project"
author: "BA888_Team3"
date: "4/3/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install packages
```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(tidytext)
library(skimr)
library(dplyr)
library(purrr)
library(cluster)
library(factoextra)
library(corrplot)
library(arules)
library(arulesViz)
library(psych)
library(GPArotation)
library(leaflet)
library(tm)
library(wordcloud)
library(quanteda)
library(topicmodels)
library(ggplot2)
```

## load olist datasets
```{r}
customer <- read.csv('Data/olist_customers_dataset.csv')
order <- read.csv('Data/olist_orders_dataset.csv')
order_item <- read.csv('Data/olist_order_items_dataset.csv')
order_payment <- read.csv('Data/olist_order_payments_dataset.csv')
order_reviews <- read.csv('Data/olist_order_reviews_dataset.csv')
order_review_translated <- read.csv('Data/Translated_reviews - order_review_translated.csv')

product <- read.csv('Data/olist_products_dataset.csv')
location <- read.csv('Data/olist_geolocation_dataset.csv')
sellers <- read.csv('Data/olist_sellers_dataset.csv')
```

# load marketing funnel dataset
```{r}
cd <- read.csv("Data/olist_closed_deals_dataset.csv")
mql <- read.csv("Data/olist_marketing_qualified_leads_dataset.csv")
marketing_funnel<- merge(cd, mql, by="mql_id")

location1 = location %>% group_by(geolocation_zip_code_prefix) %>% 
  summarize(mean_lat = mean(geolocation_lat),
            mean_long = mean(geolocation_lng))
```

## join all the dataset
```{r setup, include=FALSE}
p<- left_join(left_join(left_join(customer, order),order_item),product)
transaction <- left_join(p,order_payment)
transaction1 <- left_join(transaction,location1,
                          by = c("customer_zip_code_prefix"="geolocation_zip_code_prefix"))
transaction2 <- na.omit(left_join(transaction1,sellers))

transaction <- transaction2 %>%
  mutate(major_state = if_else(customer_state == c('SP','RJ','MG','BA','PA','PE'), 1, 0))
transaction_review<-left_join(transaction, order_reviews, by= c("order_id"="order_id"))

```

## Clean transaction date
```{r}
transaction$order_estimated_delivery_date <- as.POSIXct(transaction$order_estimated_delivery_date, format="%Y-%m-%d %H:%M:%S")
transaction$order_approved_at <- as.POSIXct(transaction$order_approved_at, format="%Y-%m-%d %H:%M:%S")




transaction$order_delivered_customer_date <- as.POSIXct(transaction$order_delivered_customer_date, format="%Y-%m-%d %H:%M:%S")
## using ceiling() to get the smallest intergers not less than the corresponding elements of x
transaction$deliverd_difftime <- ceiling(as.numeric(difftime(transaction$order_delivered_customer_date ,transaction$order_estimated_delivery_date), units = "days"))



transaction$delivered_days <- as.numeric(difftime(transaction$order_delivered_customer_date ,transaction$order_approved_at), units = "days")


transaction <- na.omit(transaction)

```

## Merge and create csv file
```{r}
final <- merge(marketing_funnel, transaction, by="seller_id")
translated_review_clean <- order_review_translated %>% 
  select(order_id,review_score,review_comments)

final_withreview <- merge(final,translated_review_clean, by="order_id")

final_withreview <- left_join(final,translated_review_clean, by="order_id")
write_csv(final_withreview,"final_dataset.csv")

useful_var<-c("price","deliverd_difftime","delivered_days",
              "payment_value","freight_value","product_category_name",
              "product_name_lenght","product_description_lenght","product_photos_qty",
              )

colnames(final_withreview)
```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

## Text Analysis

```{r}
## Text Analysis

reviews <- read_csv("Data/olist_order_reviews_dataset.csv")

order_reviews = na.omit(reviews)
order_reviews$review_comment_message = tolower(order_reviews$review_comment_message)
order_reviews1 <- order_reviews %>%
  unnest_tokens(token, review_comment_message) 

stopwords::stopwords_getsources() 
stopwords::stopwords_getlanguages("misc") 
stopwords::stopwords_getlanguages("snowball") 
stopwords::stopwords_getlanguages("stopwords-iso") 
stopwords::stopwords_getlanguages("smart") 
stopwords::stopwords("portuguese")->porStopwords
porStopwords<-as.data.frame(porStopwords)
names(porStopwords)[1]<-"word"

order_reviews2 <- order_reviews1 %>%
  anti_join(porStopwords, by = c('token' = 'word')) 
order_reviews_sum <- order_reviews2 %>%
  group_by(token) %>%
  count(sort = T)

## Word Cloud Plot
wordcloud(words = order_reviews_sum$token,
          freq = order_reviews_sum$n, min.freq = 10, max.words = 50)

## LDA model
order_reviews_corpus <- corpus(order_reviews$review_comment_message) 
order_reviews_corpus1 <- tm_map(order_reviews_corpus, removeWords, porStopwords)

summary(order_reviews_corpus, n = 20, showmeta = T) 
order_reviews_dfm <- dfm(order_reviews_corpus,remove_punct= T,remove = c(stopwords::stopwords("portuguese"),"é"), remove_numbers= T, remove_symbols= T) %>%
  dfm_trim(min_termfreq = 2, max_docfreq = .5,
           docfreq_type = "prop") 
order_reviews_dtm <- convert(order_reviews_dfm, 'topicmodels')
order_reviews_lda <- LDA(order_reviews_dtm, k = 2, control = list(seed = 729))
terms(order_reviews_lda, 10) ->topicsPro
```

